declare module "../generated/prisma" {
  /**
   * Minimal PrismaClient typing used for this assignment.
   * The real client will be generated by `prisma generate`.
   */
  export class PrismaClient {
    transcript: {
      findUnique(args: any): Promise<any | null>;
      create(args: any): Promise<any>;
    };

    $disconnect(): Promise<void>;
  }

  export enum TaskStatus {
    ready = "ready",
    blocked = "blocked",
    error = "error",
  }

  export interface Task {
    id: string;
    description: string;
    priority: "low" | "medium" | "high";
    dependencies: unknown;
    status: TaskStatus;
  }
}
